site_name: Learning Journal
site_url: https://localhost:8000/
theme: material
nav:
  - Home: 'index.md'
  - Redux Basics: 'pages/redux_store.md'
  - Node.js: 'pages/nodeJS.md'
  - jQuery: 'pages/jQuery.md'
  - Javascript Memory management: 'pages/js_memory.md'
  - Testing: 'pages/testing.md'
